version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env.local
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: "db"
      DB_USERNAME: "admin"
      DB_PASSWORD: "admin"
      DB_HOST: "db"
      DB_PORT: "7000"
      AUTH_KEY: "secretkey"
      ACCESS_TOKEN_EXPIRY: 30
      SESSION_KEY: "secretkey"
      DATABASE_URL: "postgresql://admin:admin@db/db"
  
  frontend-reviews:
    build:
      context: ./review-dashboard
    env_file:
      - .env.local
    ports:
      - "3000:3000"
  
  frontend-flex:
    build:
      context: ./flexclone
    env_file:
      - .env.local
    ports:
      - "4000:4000"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    environment:
      DB_USERNAME: "admin"
      DB_PASSWORD: "admin"
      DB_NAME: "db"
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init:/docker-entrypoint-initdb.d

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   depends_on:
  #     - db

volumes:
  postgres_data: